name: StackstormOnAKS
on: [push]
jobs:
  job1:
    name: stackstorm-aks
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: main
      - name: Provision AKS
        run: cd main && ./1-provision-aks.sh
      - name: Post Provision
        run: cd main && ./2-post-provision.sh
      - name: Deploy with Helm
        run: cd main && ./3-helm-deploy.sh
      - name: Integration Tests
        run: cd main && ./4-helm-test.sh
      - name: Validate Tests with st2client
        run: cd main && ./5-st2client-validate.sh